1. Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida
de matriz en la que cada elemento es una suma de elementos de las 2
matrices? (solo puede usar numpy como librería, si realiza la matriz
con otro paquete el ejercicio no es válido)

In [5]:
import numpy as np

a = np.array([[5,8,9],[8,7,3]])
b = np.array([[14,15,6],[32,5,65]])
c = a+b

print(c)

[[19 23 15]
 [40 12 68]]


2. Cree una matriz de identidad de dimensión 4.

In [8]:
identity_4 = np.identity(4)
print(identity_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


3. Convierte una matriz numpy binaria (que contiene solo 0 y 1) en una
matriz numpy booleana.

In [15]:
identity_5 = np.identity(5, dtype=bool)
print(identity_5)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


4. Genere una secuencia de números en forma de matriz numpy de 0 a
100 con espacios de 2 números, por ejemplo: 0, 2, 4 ...

In [18]:
np_range = np.arange(0,102,2)
print(np_range)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
